### PR TITLE
Integrate the landing page to display all red-flags and interventions

### PR DESCRIPTION
**Pull request by richien**
### What does this PR do?
 Integrate the landing page to API for display of incidents
### Description of Task to be completed?

- [x] Write a script in javascript that calls the API endpoints that get
all red flags and interventions.
- [x] If the response is successful and data returned, display the data on the
landing page
- [x] If no data is returned, display the appropriate message.

## How should this be manually tested?
- [iReporter](https://richien.github.io/iReporter/UI/signin.html)
- The link above it the iReporter application hosted on GitHub pages
- Enter the following credentials
  `Email: test@email.com`
  `Password: Enter123` 
- You are then redirected to the landing page.
- Click on the RedFlags button to view a list of
recent red flags
- Click on the list item to view more details
## What are the relevant pivotal tracker stories?
#163838256

## Reviewers
Kindly review this PR and share feedback. Thank you.
@nadralia
@sebbss
@Kalsmic
@Rhytah
@NicholusMuwonge
@llwasampijja
@aldookware

### CODE REVIEW

**Comment by Rhytah** [comment]
Great work on the navigation and the UI displays the information when the respective buttons are clicked , though it seems to be displaying static data. And not data I report

**Comment by richien** [comment]
> Great work on the navigation and the UI displays the information when the respective buttons are clicked , though it seems to be displaying static data. And not data I report

Thank you Rhytah, the data is not static. It is picked from the database. However, you cannot create an 
Incident because I have not yet implemented that feature

**Comment by Rhytah** [comment]
> > Great work on the navigation and the UI displays the information when the respective buttons are clicked , though it seems to be displaying static data. And not data I report
> 
> Thank you Rhytah, the data is not static. It is picked from the database. However, you cannot create an
> Incident because I have not yet implemented that feature

Okay. Makes sense now.

**Comment by kalsmic** [comment]
True,@richien, I was able to view all the red-flags and interventions. However, I look forward to testing this feature again when you implement the feature for adding an incident so that I can really give you clear affirmation that indeed this works as expected.

**Pull request merged**
