### PR TITLE
Intergate signup UI feature to signup API endpoint.

### PR DESCRIPTION
**Pull request by richien**
### What does this PR do?
 Integrate signup feature to the iReporter API endpoint
### Description of Task to be completed?

- [x] Write a script in javascript that retrieves user input form data
and calls the signup API endpoint with that data in the request body.
- [x] If the response is successfull, create a session with the user's ID
and token and redirect to the landing page
- [x] If and error response is returned, display the appropriate error message
for the user to act upon.

## How should this be manually tested?
- [iReporter](https://richien.github.io/iReporter/UI/signup.html)
- The link above it the iReporter application hosted on github pages
- Simply fill in the form and submit 
## What are the relevant pivotal tracker stories?
#163705676

##Reviewers
Kindly review this PR and share feedback. Thank you.
@nadralia
@sebbss
@Kalsmic
@Rhytah
@NicholusMuwonge
@llwasampijja
@Aldo

### CODE REVIEW

**Comment by nadralia** [comment]
Nice work so far.. But you wouldn't want to display server errors to your clients or users..(the catch part of your fetch display servers errors to the user

**Comment by kalsmic** [comment]
@richien, the functionality for Email validation and duplicate user check works fine well, however, you should consider adding some validation to the signup. I was able to create an account with 12345 as username, first name, and last name, other names.

**Comment by richien** [comment]
> Nice work so far.. But you wouldn't want to display server errors to your clients or users..(the catch part of your fetch display servers errors to the user

Thanks for the feedback. I have taken note of this.

**Comment by richien** [comment]
> @richien, the functionality for Email validation and duplicate user check works fine well, however, you should consider adding some validation to the signup. I was able to create an account with 12345 as username, first name, and last name, other names.

Thanks @kalsmic . There is quite abit that is not yet done. I am aiming to develop a minimum viable app first then refractor. I have made note of this, thank you for the feedback.

**Pull request merged**
